apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name : {{ .Values.app.name }}
          image: {{ .Values.app.container.image }}
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "9000Mi"
              cpu: "2000m" 
          env:
          {{- range $item := .Values.configMap }}
            - name: {{ $item.name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.app.config.name }}
                  key: {{ $item.key }}
          {{- end }}
          {{- range $item := .Values.Secret }}
            - name: {{ $item.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.app.secrets.name }}
                  key: {{ $item.key }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.app.volume.volumemountname1 }}
              mountPath: {{ .Values.app.volume.mountPath1 }}
      volumes:
        - name: {{ .Values.app.volume.volumemountname1 }}
          persistentVolumeClaim:
            claimName: {{ .Values.app.volume.claimname1 }}
      imagePullSecrets:
        - name: {{ .Values.app.container.imagePullSecrets }}