apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secrets.name }}
  namespace: {{ .Values.app.namespace }}
data:
 {{- range .Values.app.secrets.data }}
  {{ .key }}: {{ .value | b64enc }}
 {{- end}}